pub enum IconKind {
    //slightly larger title screen icons, spacing for 17x16
    Enter,
    Gold,
    Rankings,
    Badges,
    News,
    Changes,
    Prefs,
    Shpx,
    Journal,
    //grey icons, mainly used for buttons, spacing for 16x16
    Exit,
    Display, //2 separate images, changes based on orientation
    DisplayLand,
    DisplayPort,
    Data,
    Audio,
    Langs,
    Controller,
    Keyboard,
    Stats,
    ChallengeGrey,
    ScrollGrey,
    Seed,
    LeftArrow,
    RightArrow,
    Calendar,
    Chevron,
    //misc larger icons, mainly used for buttons, tabs, and journa
    Target,
    Info,
    Warning,
    Unchecked,
    Checked,
    Close,
    Plus,
    Repeat,
    Arrow,
    ChallengeColor,
    ScrollColor,
    Copy,
    Paste,
    BackpackLrg,
    Talent,
    Magnify,
    Snake,
    Buffs,
    Catalog,
    Alchemy,
    Grass,
    Stairs,
    StairsChasm,
    StairsWater,
    StairsGrass,
    StairsDark,
    StairsLarge,
    StairsTraps,
    StairsSecrets,
    WellHealth,
    WellAwareness,
    SacrificeAltar,
    DistantWell,
    //smaller icons,variable spacing
    Skull,
    Busy,
    Compass,
    Sleep,
    Alert,
    Lost,
    Depth, //depth icons have three variants,for regular se
    DepthChasm,
    DepthWater,
    DepthGrass,
    DepthDark,
    DepthLarge,
    DepthTraps,
    DepthSecrets,
    ChalCount,
    CoinSml,
    EnergySml,
    Backpack,
    SeedPouch,
    ScrollHolder,
    WandHolster,
    PotionBandolier,
    //icons that appear in the about screen,variable spacing
    Libgdx,
    Aleks,
    Wata,
    Celesti,
    Kristjan,
    CubeCode,
    Purigro,
    ARCNOR,
}


